version: '3.7'
services:
  db:
    image: postgres
    container_name: 'dbapi_nestjs_gql'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: dbapi_nestjs_gql
    volumes:
      - ./pgdata:/var/lib/postgresql/pg
    networks:
      - finance
  web:
    image: carloscortez/api_nestjs_gql
    env_file:
      - production.env
    environment:
      - NODE_ENV=production
    depends_on:
      - db
    ports:
      - '4000:4000'
    networks:
      - apinestjsgql

volumes:
  pgdata:

networks: apinestjsgql:
